### PR TITLE
Include locales

### PR DESCRIPTION
**Pull request by tmmgrafikr**
Alternative fix to match of locales also.

I can't seem to figure out a better way to create the regex. Some mentions the `escapeRegExp` method, but just seems to break it even more, to use in native `RegExp` constructor.

_Primarily this that seems a bit hacky_
https://github.com/grafikr/shopify-actions/compare/main...tmmgrafikr:regex-locales-fix?expand=1#diff-4fa79321e9214ef3bbc1023620593e98a1aec4f33f03319d425b0c3b49d323a0R6-R9

Alternativ you can also add a test npm script, made my life easier.
```js
"test": "yarn build && node dist/index.js"
```

### CODE REVIEW

**Comment by andershagbard** [comment]
> Primarily this that seems a bit hacky

It's transformed into JS from https://github.com/Shopify/themekit. Can't remember exactly where the code was.

**Comment by andershagbard** [comment]
Does this work with `templates/*.json` for example?

**Comment by tmmgrafikr** [comment]
@andershagbard Yes. Tested on this theme: https://grafikr-test-store.myshopify.com/admin/themes/130079195289
This following converts wildcards into valid RegExp: https://github.com/grafikr/shopify-actions/pull/44/files#diff-4fa79321e9214ef3bbc1023620593e98a1aec4f33f03319d425b0c3b49d323a0R4

So `templates/*.json` becomes `/templates\/(.*?).json/g` which is valid native RegExp

**Review by andershagbard — APPROVED** [review]

**Comment by tmmgrafikr** [comment]
@andershagbard Should i merge it? Not sure when/if you want us to merge PRs 😄

**Pull request merged**
